name: Build Windows EXE

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-mingw-w64 g++-mingw-w64 qtbase5-dev qtbase5-dev-tools qt5-qmake
      - name: Configure
        run: |
          qmake -set CROSS_COMPILE x86_64-w64-mingw32-
          qmake -spec win32-g++ CONFIG+=release -o Makefile fvp.pro
      - name: Build
        run: make -j$(nproc)
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: fvp-exe
          path: release/fvp.exe

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: fvp-exe
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@master
        with:
          files: dist/fvp.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
