name: Build Windows EXE

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install MXE cross toolchain
        run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common curl gnupg
          curl -fsSL https://pkg.mxe.cc/repos/apt/client-conf/mxeapt.gpg | sudo gpg --dearmor -o /usr/share/keyrings/mxe.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/mxe.gpg] http://pkg.mxe.cc/repos/apt focal main" | sudo tee /etc/apt/sources.list.d/mxe.list
          sudo apt-get update -y
          sudo apt-get install -y mxe-x86-64-w64-mingw32.static-gcc mxe-x86-64-w64-mingw32.static-qtbase mxe-x86-64-w64-mingw32.static-qttools
          echo "/usr/lib/mxe/usr/bin" >> $GITHUB_PATH
      - name: Configure
        run: |
          /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake -spec win32-g++ CONFIG+=release -o Makefile fvp.pro
      - name: Build
        run: make -j$(nproc)
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: fvp-exe
          path: release/fvp.exe

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: fvp-exe
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@master
        with:
          files: dist/fvp.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
